# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('dimension', models.CharField(default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('equipmentType', models.IntegerField(default=0)),
                ('cntDefault', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MoveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('remainCnt', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Equipment')),
            ],
        ),
    ]
