# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('completeCnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='two.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='needStruct',
            field=models.ManyToManyField(blank=True, default=None, related_name='needStructStandartWork12', to='two.NeedStruct'),
        ),
    ]
